// @taskd/extension-api — the contract between the taskd web app and its
// extensions. An extension is an ESM bundle at <extension>/web/main.js whose
// default export is a TaskdExtension; the host imports it at startup and
// calls register(api).
//
// Build recipe (esbuild): bundle with react and react/jsx-runtime aliased
// to the shims in this package, so extension components share the host's
// React instance (a second React copy would break hooks):
//
//   esbuild src/main.tsx --bundle --format=esm --outfile=web/main.js \
//     --alias:react=@taskd/extension-api/react-shim.js \
//     --alias:react/jsx-runtime=@taskd/extension-api/jsx-shim.js
//
// Styling: the host's Tailwind classes are NOT part of the contract (the
// core bundle only contains classes core uses). Style with inline styles
// and the host's CSS custom properties, which are theme-aware:
//   --bg --surface --ink --muted --faint --line --accent --warn
// and fonts: "IBM Plex Sans" (UI) / "IBM Plex Mono" (data).

import type { ComponentType } from "react";

/** The task message, as generated by protoc-gen-es from proto/task/task.proto. */
export interface Task {
  id: string;
  title: string;
  notes: string;
  labels: string[];
  dueTime?: { seconds: bigint; nanos: number };
  completedTime?: { seconds: bigint; nanos: number };
  source: string;
  externalRef: string;
  /** Source-owned extension data (opaque JSON). */
  externalData?: Record<string, unknown>;
  /** User-owned extension data (opaque JSON). Namespace your keys. */
  userData?: Record<string, unknown>;
  revision: bigint;
  createTime?: { seconds: bigint; nanos: number };
  updateTime?: { seconds: bigint; nanos: number };
}

/** Extra presentation a matching task's list row gets. */
export interface RowMeta {
  /** Short mono text shown where the due date normally is (e.g. "9:30–9:45"). */
  timeText?: string;
  /** Small muted text after the title (e.g. "taskd#41"). */
  subtitle?: string;
  /** Additional label-style chips (plain strings). */
  extraChips?: string[];
  /** Emoji or 1–2 character marker shown before the title. */
  icon?: string;
}

export interface Presenter {
  /** Which tasks this presenter handles, e.g. t.source.startsWith("gcal"). */
  match(task: Task): boolean;
  /** Row customization; return {} for none. */
  rowMeta?(task: Task): RowMeta;
  /** Rendered inside the detail panel for matching tasks. */
  DetailSection?: ComponentType<{ task: Task; api: ExtensionAPI }>;
}

/** A whole view contributed to the app: sidebar entry + URL (?ext=<id>). */
export interface ExtensionView {
  id: string;
  title: string;
  Component: ComponentType<{ api: ExtensionAPI }>;
}

export interface TaskPatch {
  title?: string;
  notes?: string;
  labels?: string[];
  /** undefined = untouched; null = clear. */
  due?: Date | null;
  completed?: boolean;
  /** Whole-field replace (merge by spreading task.userData). null clears. */
  userData?: Record<string, unknown> | null;
  expectedRevision?: bigint;
}

export interface ExtensionAPI {
  registerPresenter(p: Presenter): void;
  registerView(v: ExtensionView): void;

  /** Live replica of ACTIVE tasks — hooks usable in extension components. */
  hooks: {
    /** All active tasks; re-renders on any change (watch-fed). */
    useTasks(): Task[];
    /** A slow clock (default 30s tick) for relative-time rendering. */
    useNow(): Date;
  };

  /** Mutations, optimistic against the replica. */
  store: {
    create(fields: { title: string; notes?: string; labels?: string[]; due?: Date }): Promise<Task>;
    update(id: string, patch: TaskPatch): Promise<void>;
    delete(id: string): Promise<void>;
  };

  /** The full generated TaskService client, for anything else. */
  client: unknown;

  ui: {
    /** Opens the host's detail panel for a task. */
    openTask(id: string): void;
  };

  format: {
    /** proto Timestamp → Date (undefined-safe). */
    tsDate(ts?: { seconds: bigint; nanos: number }): Date | undefined;
    /** "project:home" → { ns: "project", val: "home" }. */
    chipParts(label: string): { ns?: string; val: string };
  };
}

export interface TaskdExtension {
  name: string;
  register(api: ExtensionAPI): void;
}
